# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Docker compose
  jobs:  
  - job: Build
    displayName: Build & Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |      
          chmod 777 release.sh
          ./build.sh
      env:
        buildversion: $(Build.BuildId)
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          chmod 777 release.sh
          docker login -u $(docker_user) -p $(docker_password)
          ./release.sh
      env:
        buildversion: $(Build.BuildId)
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: './k8sfiles'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'