# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Docker compose
  jobs:  
  - job: Build
    displayName: Build & Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'docker_hub_qm'
        dockerComposeFile: '**/docker-compose.yml'
        projectName: 'qualitymanager'
        action: 'Build services'
        includeSourceTags: true
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'docker_hub_qm'
        dockerComposeFile: '**/docker-compose.yml'
        projectName: 'qualitymanager'
        action: 'Push services'
        includeSourceTags: true