version: "3.3"
services:
  mainbuild:
    build:
      context: .
      dockerfile: Dockerfile
    image: "pranavkakde/qualitymanager_mainbuild"
  auth-services:
    build:
      context: ./packages/Services/AuthServices
      dockerfile: Dockerfile        
    ports:
      - "8181:8181"
    depends_on:
      - mainbuild
    image: "pranavkakde/qualitymanager_auth-services"        
  gateway-services:
    build:
      context: ./packages/Services/GatewayServices
      dockerfile: Dockerfile        
    ports:
      - "10104:10104"
    depends_on:
      - mainbuild      
    image: "pranavkakde/qualitymanager_gateway-services"
  client-services:
    build:
      context: ./packages/Services/ClientManagementServices
      dockerfile: Dockerfile      
    ports:
      - "7778:7778"
    depends_on:
      - mainbuild      
    image: "pranavkakde/qualitymanager_client-services"
  defect-services:
    build:
      context: ./packages/Services/DefectManagementServices
      dockerfile: Dockerfile
    ports:
      - "7779:7779"
    depends_on:
      - mainbuild
    image: "pranavkakde/qualitymanager_defect-services"
  project-services:
    build:
      context: ./packages/Services/ProjectManagementServices
      dockerfile: Dockerfile
    ports:
      - "7782:7782"
    depends_on:
      - mainbuild
    image: "pranavkakde/qualitymanager_project-services"
  release-services:
    build:
      context: ./packages/Services/ReleaseManagementServices
      dockerfile: Dockerfile
    ports:
      - "7781:7781"
    depends_on:
      - mainbuild
    image: "pranavkakde/qualitymanager_release-services"
  testcase-services:    
    build:
      context: ./packages/Services/TestManagementServices
      dockerfile: Dockerfile
    ports:
      - "7784:7784"        
    depends_on:
      - mainbuild      
    image: "pranavkakde/qualitymanager_testcase-services"
  testsuite-services:
    build:
      context: ./packages/Services/TestSuiteManagementServices
      dockerfile: Dockerfile
    ports:
      - "7780:7780"
    depends_on:
      - mainbuild
    image: "pranavkakde/qualitymanager_testsuite-services"
  user-services:
    build:
      context: ./packages/Services/UserManagementServices
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    depends_on:
      - mainbuild
    image: "pranavkakde/qualitymanager_user-services"
networks:
  default:
    driver: host
