version: "3.3"
services:
  mainbuild:
    build:
      context: .
      dockerfile: Dockerfile
  client-services:
    build:
      context: ./packages/Services/ClientManagementServices
      dockerfile: Dockerfile
  defect-services:
    build:
      context: ./packages/Services/DefectManagementServices
      dockerfile: Dockerfile
  project-services:
    build:
      context: ./packages/Services/ProjectManagementServices
      dockerfile: Dockerfile
    ports:
      - "7782:7782"
  release-services:
    build:
      context: ./packages/Services/ReleaseManagementServices
      dockerfile: Dockerfile
    ports:
      - "7781:7781"
  testcase-services:    
    build:
      context: ./packages/Services/TestManagementServices
      dockerfile: Dockerfile
    ports:
      - "7784:7784"        
  testcase-services:
    build:
      context: ./packages/Services/TestManagementServices
      dockerfile: Dockerfile
    ports:
      - "7780:7780"
  user-services:
    build:
      context: ./packages/Services/UserManagementServices
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
networks:
  default:
    driver: host