apiVersion: v1
kind: Service
metadata:
  name: backendservices
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - name: client-services-port
      port: 7778
      targetPort: 7778
    - name: user-services-port
      port: 7777
      targetPort: 7777
    - name: project-services-port
      port: 7782
      targetPort: 7782      