apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-services
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: user-services
          image: pranavkakde/qualitymanager_user-services
          env:
            - name: DBINSTANCE
              value: "192.168.20.11\\SQLEXPRESS"
            - name: DATABASE
              value: "TMTool"
            - name: DBUSER
              value: "nodeuser"
            - name: DBPASSWORD
              value: "nodeuser"          
          ports:
            - containerPort: 7777
        - name: client-services
          image: pranavkakde/qualitymanager_client-services
          env:
            - name: DBINSTANCE
              value: "192.168.20.11\\SQLEXPRESS"
            - name: DATABASE
              value: "TMTool"
            - name: DBUSER
              value: "nodeuser"
            - name: DBPASSWORD
              value: "nodeuser"          
          ports:
            - containerPort: 7778