export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE'    
};

export const authConstants = {
    TOKEN_REQUEST: 'TOKEN_REQUEST',
    TOKEN_SUCCESS: 'TOKEN_SUCCESS',
    TOKEN_FAILURE: 'TOKEN_FAILURE',    
    VALIDATE_TOKEN: 'VALIDATE_TOKEN',
    TOKEN_REMOVED: 'TOKEN_REMOVED'
};

export const listConstants = {
    ITEM_CLICKED: 'ITEM_CLICKED',
    SET_APPBAR: 'SET_APPBAR'
}

export const tsConstants = {
    GETALL_TS_REQUEST: 'TS_GETALL_REQUEST',
    GETALL_TS_SUCCESS: 'TS_GETALL_SUCCESS',
    GETALL_TS_FAILURE: 'TS_GETALL_FAILURE',
    GETBYID_TS_REQUEST: 'TS_GETBYID_REQUEST',
    GETBYID_TS_SUCCESS: 'TS_GETBYID_SUCCESS',
    GETBYID_TS_FAILURE: 'TS_GETBYID_FAILURE'
}

export const projectConstants = {
    GETALL_PROJ_SUCCESS: 'GETALL_PROJ_SUCCESS',
    GETALL_PROJ_FAILURE: 'GETALL_PROJ_FAILURE'
}